add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'
format = "$directory$git_branch$git_status$character "
right_format = "$cmd_duration"

[line_break]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_symbol = "../"

[git_status]
style = "bright-blue"
format = "([$ahead_behind$conflicted$staged$modified$untracked$stashed]($style)) "

ahead    = "[^${count}](bright-green) "
behind   = "[v${count}](bright-red) "
diverged = "[^${ahead_count} v${behind_count}](bold red) "

conflicted = "[=${count}](bold red) "
staged     = "[+${count}](bright-green) "
modified   = "[!${count}](bright-yellow) "
untracked  = "[?${count}](dim white) "
stashed    = "[*${count}](dim yellow) "

renamed = ""
deleted = ""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold yellow)"

[cmd_duration]
min_time = 500
style = "yellow"
format = "[$duration]($style)"

