# No agregar una línea en blanco al inicio para ahorrar espacio
add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'
# Ejemplo con más info a la derecha
format = "$directory$git_branch$git_status$character "
right_format = "$cmd_duration"

[line_break]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_symbol = "../"

[git_branch]
format = "[$symbol $branch]($style) "
symbol = ""
style = "bold purple"

[git_status]
style = "bold red"
format = "([$ahead_behind$staged$modified]($style)) "

ahead = "[^${count}](bright-green) "
behind = "[v${count}](bright-red) "

stashed = "* ${count}"
staged = "[+${count}](bright-green) "
modified = "[!${count}](bright-yellow) "

untracked = ""
conflicted = ""
renamed = ""
deleted = ""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold yellow)"

[cmd_duration]
min_time = 500
style = "yellow"
format = "[$duration]($style)"

